apiVersion: apps/v1
kind: Deployment
metadata:
  name: quoterepo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quoterepo
  template:
    metadata:
      labels:
        app: quoterepo
    spec:
      containers:
      - name: quoterepo
        image: quoteserveracr.azurecr.io/quoterepo:v2
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 250m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: quoterepo
spec:
  type: LoadBalancer
  ports:
  - port: 3000
  selector:
    app: quoterepo