name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t raymondvaldez/quoterepo .
    
    - name: runTheContainer
      run: docker run -d -p 3000:3000 raymondvaldez/quoterepo

    #not working
    #- name: showCurrentContext
    #  run: docker context show

    #- name: list crunning containers
    #  run: docker ps
