name: build_deploy_aks
on: [push]

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          cd ServerSide
          node testAllQuotes.js

  Build-and-Run:
    needs: run-unit-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code 
        uses: actions/checkout@v3

      - name: Azure login
        id: login
        uses: azure/login@v1.4.3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name : Login to ACR
        run : az acr login --name ${{ secrets.registry }}

      - name : Build Dockerfile
        run: docker build . --no-cache -t quoteserveracr.azurecr.io/quoterepo:${{ github.sha }}

      - name : Push to ACR
        run : docker push quoteserveracr.azurecr.io/quoterepo:${{ github.sha }}

      #Set the target AKS cluster context which will be used by other actions or run any kubectl commands.
      - name: Set AKS context
        id: set-context
        uses: azure/aks-set-context@v3
        with:
          resource-group: '${{ secrets.resource_group }}' 
          cluster-name: '${{ secrets.cluster_name }}'

      #- name: Setup kubectl
      #  id: install-kubectl
      #  uses: azure/setup-kubectl@v3

      - name: Deploy to AKS
        id: deploy-aks
        uses: Azure/k8s-deploy@v4
        with:
          namespace: 'default'
          manifests: |
             manifest-file1.yaml
          images: '${{ secrets.registry }}.azurecr.io/quoterepo:${{ github.sha }}'
          pull: false

